name: ai-investment-advisor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - scipy>=1.10.0
  - requests>=2.31.0
  - pip:
    - yfinance>=0.2.20
    - reportlab>=4.0.0
    - python-pptx>=0.6.21
    - plotly>=5.15.0